spring:
  datasource:
    url: jdbc:postgresql://localhost:25432/massage?charSet=utf-8
    driver-class-name: org.postgresql.Driver
    username: massage
    password: massage
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
